export const figures = {
  sharePriceFrom: 100,
  adrLow: 100,
  adrHigh: 132,
  occupancyLow: 33,
  occupancyHigh: 44,
  yieldLow: 6,
  yieldHigh: 10,
  profitShareInvestor: 80,
  profitShareOperator: 20,
  tiers: [
    {
      name: 'Starter',
      shares: 12,
      capsules: 1,
      priceFrom: 1200,
      featured: false,
      sharesLabel: '12 shares',
      capsulesLabel: '≈ 1 capsule',
      priceLabel: 'from $1,200',
      yieldLabel: '6–10% target',
      note: 'A single capsule, fractionally owned. Quarterly distributions.',
    },
    {
      name: 'Cluster',
      shares: 48,
      capsules: 4,
      priceFrom: 4800,
      featured: true,
      sharesLabel: '48 shares',
      capsulesLabel: '≈ 4 capsules',
      priceLabel: 'from $4,800',
      yieldLabel: '6–10% target',
      note: 'A row within the village. Smoother occupancy across units.',
    },
    {
      name: 'Block',
      shares: 120,
      capsules: 10,
      priceFrom: 12000,
      featured: false,
      sharesLabel: '120 shares',
      capsulesLabel: '≈ 10 capsules',
      priceLabel: 'from $12,000',
      yieldLabel: '6–10% target',
      note: 'A whole block. Priority on new phases and buy-back window.',
    },
  ],
  contacts: {
    email: 'info@swiftholdings.org',
    phoneGh: '+233 544 101016',
    phoneCa: '+1 437 421 0963',
    address: '20 Edmonton St, Madina, Accra',
  },
} as const;

export type Figures = typeof figures;
